all:
	latex segp2-08-s2-m4-report-fl-20080815.tex
	latex segp2-08-s2-m4-report-fl-20080815.tex
	dvipdf segp2-08-s2-m4-report-fl-20080815.dvi
	evince segp2-08-s2-m4-report-fl-20080815.pdf &


clean:
	rm *.aux &
	rm *.dvi &
	rm *.log &
	rm *~ &

